extends Node3D
class_name Component_Suspension
var component_name: String = "Suspension"

#These are for components
@export var price: int = 1000 #arbitrary
@export var weight: float = 100 #kg
@export var ideal_weight_capacity: float = 5000 #kg
@export var maximum_weight_capacity: float = 12000 #kg
@export var track_width_max: float = 500 #mm
@export var track_ground_length: float = 4.0 #mm
@export var length: float = 200 #mm
@export var width: float = 200
@export var depth: float = 200
@export var long_name: String = "Super Fucking Annoying Suspension: Take 1 (of 4)"
@export var short_name: String = "SUS01"
@export var description: String = "This suspension was the fucking death of me I swear"
@export var engine_driven: bool = true

#These are things to make this fucked choo-choo train work
var contacts: float = 0.0
var track_segmented_length: float = 100.0

var RPM_engine_incoming: float = 0.0
var RPM_wheel_outgoing: float = 0.0
var engine_max_force: float = 0.0

var turn_left: bool = false
var turn_right: bool = false

var brakes_on: bool = false
var is_left: bool = false
var is_colliding: bool = false

var debug: bool = false

var sprocket_radius: float = 0.5

#Carriers
var sprocket: Node3D = null
var idler: Node3D = null
var suspension_wheels: Array = []
var running_wheels: Array = []
var hidden_wheels: Array = []
var suspension_wheels_count: float = 1.0

var parent: Node3D


func _ready() -> void:
	if owner != null: await owner.ready
	sprocket = get_node_or_null("Sprocket")
	idler = get_node_or_null("Idler")
	suspension_wheels = $Suspension_Wheels.get_children()
	hidden_wheels = $Hidden_Wheels.get_children()
	
	if parent == null:
		parent = GlobalFunctions.grab_rigid_parent(self)
	
	#Assign Parents
	sprocket.parent = parent
	idler.parent = parent
	for wheel in suspension_wheels:
		wheel.parent = parent
	for wheel in hidden_wheels:
		wheel.parent = parent
	
	if sprocket == null:
		print("NO SPROCKET ASSIGNED IN SUSPENSION")
		print(self)
		queue_free()
	if idler == null:
		print("NO IDLER ASSIGNED IN SUSPENSION")
		print(self)
		queue_free()
	if suspension_wheels.size() == 0:
		print("NO SUSPENSION WHEELS ASSIGNED IN SUSPENSION")
		print(self)
		queue_free()
	
	sprocket_radius = sprocket.wheel_radius
	suspension_wheels_count = suspension_wheels.size()
	
	#some shit later to run through the track path
	#some shit later to get the curve generated by the track path
	#hold on to some of those track path variables for later; don't keep rebaking that shit
	
	if position.x < 0.0: is_left = true
	
	#if is_left:
		#var meshes: Array = find_children("*","MeshInstance3D",1,1)
		#for m in meshes:
			#m.scale.x = m.scale.x * -1

func _physics_process(delta: float) -> void:
	update_children()
	
func _process(delta: float) -> void:
	pass
	

func update_children():
	RPM_wheel_outgoing = abs(sprocket.return_RPM_free())
	var sprocket_modified_RPM: float = RPM_engine_incoming / sprocket_radius
	contacts = 0.0
	for w in suspension_wheels:
		if w.is_colliding: contacts += 1.0
	if sprocket.is_colliding: contacts += 1.0
	if idler.is_colliding: contacts += 1.0
	contacts = max(1.0, contacts)
		
	var modified_engine_force: float = engine_max_force / contacts
	if debug: DebugDraw2D.set_text("modified_engine_force",modified_engine_force)
	
	#if is_left and turn_left:
		#brakes_on = true
	#if not is_left and turn_right:
		#brakes_on = true
	
	for w in suspension_wheels:
		w.brakes_on = brakes_on
		w.RPM_engine_incoming = sprocket_modified_RPM * w.wheel_radius
		w.engine_incoming_force = modified_engine_force
		
	sprocket.RPM_engine_incoming = RPM_engine_incoming
	sprocket.engine_incoming_force = modified_engine_force / 2.0
	idler.RPM_engine_incoming = RPM_engine_incoming
	idler.engine_incoming_force = modified_engine_force / 2.0

	if contacts > 0.0:
		is_colliding = true
	else:
		is_colliding = false

func audio():
	pass
	
func distribute_power():
	pass
	
func wheel_rotations():
	pass
